### ISSUE TITLE
Node dependency

### ISSUE THREAD

**Issue by po5i** [TwilioDevEd/sample-template-laravel#6]
Is Node required for this project to run? if so, can you add it to the [requirements](https://github.com/TwilioDevEd/sample-template-laravel#requirements)?

**Comment by maylonpedroso** [comment]
It is in the requirements :-)

**Comment by po5i** [comment]
Oh yes! I missed mentioning which version is needed. Is there any version restriction from Laravel?

**Comment by maylonpedroso** [comment]
By Laravel documentation, mix does not require a specific version of Node :man_shrugging: 
https://laravel.com/docs/7.x/mix#installation

**Comment by po5i** [comment]
Fair enough
